### ISSUE TITLE
Install Guide Doesn't work for FreeBSD

### ISSUE THREAD

**Issue by lachlanjholmes** [LeonB/JupiterBroadcasting.bundle#1]
Hey!

I don't know how to change this or not in your doco.

Your install guide for Freesd doesn't work for when you install Plexmediaserver.

Your are referencing the wrong location when making directories, doing the find | chmods and git clone copy.

Is is the location of the plex media server plug-ins:

/usr/local/plexdata/Plex Media Server/Plug-ins/JupiterBroadcasting.bundle

I also removed the '_' in front of the _plex: _plex section aswell. 

caveats are, I had to "fix" this when using the PKGNG/PKG_ADD binary from Freebsd's repo.

Hope this helps!!!

And thanks for the work!

:)

**Comment by LeonB** [comment]
Thanks! I installed it in a custom location myself. I'm going to change it.

I emailed Plex for inclusion of this channel in the Plex app store but they
keep postponing it :(
